### ISSUE TITLE
Add Shift Dev 2019: "Metalkube: Deploy Kubernetes on Bare Metal" to conference talks section

### ISSUE THREAD

**Issue by alosadagrande** [metal3-io/metal3-io.github.io#102]
Just saw yesterday this introduction to Metal3 along with Operators, CRDs, actuators, controllers and Ironic at ShiftDev2019. IMHO looks like a good basic introduction of the components inside metal3.

Here is the link: https://www.youtube.com/watch?v=iHlaimz48vg&t=8s 

Probably good to include it in the conference talks section.

**Comment by ptrnull** [comment]
Russell, Doug, what do you thing about including the talk that @alosadagrande commented? 
What about this one? https://www.youtube.com/watch?v=QwVEl5wsQJo
/cc @russellb 
/cc @dhellmann

**Comment by russellb** [comment]
both are fine with me

**Comment by dhellmann** [comment]
I agree, those are fine.

We were going to convert all of the existing media links to blog posts, weren't we? Maybe we can use these new links as an excuse to set up the blog with a category for "talks" or something like that, to make the conversion of the old content simpler.

**Comment by stbenjam** [comment]
Any plans to revisit this?

**Comment by ptrnull** [comment]
@stbenjam Yes, we are working on it :)

**Comment by codificat** [comment]
The first video was [just published](https://metal3.io/blog/2020/01/20/metal3_deploy_kubernetes_on_bare_metal.html) and the 2nd one is in vientamese, so it has a limited target audience... suggest that we
/close
