### ISSUE TITLE
The "related entries"  inside of a post in the left side looks squeezed all together

### ISSUE THREAD

**Issue by ptrnull** [metal3-io/metal3-io.github.io#115]
The "related entries"  inside of a post in the left side looks squeezed all together.
Some space should be added between each entry.

Example: https://deploy-preview-114--metal3.netlify.com/blog/2019/05/13/the_new_stack_metal3_uses_openstack_ironic_for_declarative_bare_metal_kubernetes

**Comment by iranzo** [comment]
@matthewcarleton
