### ISSUE TITLE
http doesn't redirect to https

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/metal3-io.github.io#119]
Currently 'metal3.io' goes to http and it should redirect to https instead. Also if you keep browsing the web, it sticks with http protocol.

**Comment by russellb** [comment]
github has an option to force https, but it says:

```
 Enforce HTTPS — Not yet available for your site because the certificate has not finished being issued.
Please allow 24 hours for this process to complete. (metal3.io)

HTTPS provides a layer of encryption that prevents others from snooping on or tampering with traffic to your site.
When HTTPS is enforced, your site will only be served over HTTPS. Learn more.
```

but I haven't changed anything in weeks.

Note that cloudflare is acting as a proxy in front of the site.

**Comment by iranzo** [comment]
Does the state has changed?

**Comment by iranzo** [comment]
@russellb have you checked it in cloudflare?

![imagen](https://user-images.githubusercontent.com/312463/72058812-0fa13c00-32d1-11ea-80dc-25b6e6acbcf1.png)

**Comment by russellb** [comment]
> @russellb have you checked it in cloudflare?
> 
> ![imagen](https://user-images.githubusercontent.com/312463/72058812-0fa13c00-32d1-11ea-80dc-25b6e6acbcf1.png)

That matches the metal3.io cloudflare setting

**Comment by russellb** [comment]
@iranzo try now ...

**Comment by stbenjam** [comment]
Looks fixed to me, I get redirected to https.

/close
