### ISSUE TITLE
Add Metal³ Youtube channel to website

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#125]
Populate https://www.youtube.com/channel/UC_xneeYbo-Dl4g-U78xW15g with videos and include the link on the website.

Related with #124

**Comment by maelk** [comment]
It looks like we have duplicated youtube channel : https://www.youtube.com/channel/UC_xneeYbo-Dl4g-U78xW15g

**Comment by iranzo** [comment]
Fixed @maelk++
