### ISSUE TITLE
Some try-it comments

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/metal3-io.github.io#128]
https://github.com/metal3-io/metal3-io.github.io/blob/master/_includes/try-it.md

- Plain commands looks ok the first time, then they look weird (like many tabs):
![image](https://user-images.githubusercontent.com/346758/73261613-bd1ab780-41cc-11ea-82e9-020acbed75e8.png)

- It is not clear if v1alpha2 supports adding nodes to the running clusters or if that's v1alpha1 feature only

- No instructions on how to manage the cluster created with v1alpha2 (such as getting the kubeconfig file, how to see the nodes, etc.)

- Nodes in the cluster created with v1alpha2 are 'not ready' because there is no SDN deployed. I think it would be nice to include a default one (calico for instance)

- Another 'minor issue' would be there is no 'go to top' which means you need to scroll all the way up to see the index/header

- The `NUM_NODES` variable is used to create nodes in the cluster. It would be nice to add that variable to the try-it guide in case you want to create more nodes to play with the `machine` object (like scale up/down)

**Comment by alosadagrande** [comment]
Would make sense to write a metal3-dev-env deep dive in a blog post format and optionally supported by video? 

Later on we can check if makes sense to imporove the try-it with some information from the deep dive.

I offer my self to complete the task.

cc/ @maelk @stbenjam

**Comment by fmuyassarov** [comment]
@alosadagrande 
We have opened a [PR#130](https://github.com/metal3-io/metal3-io.github.io/pull/130) would  you please check it if serves the purpose.
