### ISSUE TITLE
No instructions on how to deploy the required assets in a vanilla k8s cluster

### ISSUE THREAD

**Issue by e-minguez** [metal3-io/metal3-io.github.io#129]
I think it would be nice if there is some document on how to deploy metal3 in a vanilla k8s cluster. The try-it doc is great but it 'hides' the procedure in the 03 script.

**Comment by maelk** [comment]
We're working on some documentation, we'll try to cover that.

**Comment by alosadagrande** [comment]
I am currently writing a deep dive about metal3-dev-env for the blog. It will detail 03 script which is in charge of creating and applying metal³ K8s objects.

Eventually, the idea is with the previous knowledge write some content showing how to deploy metal³ in an already vanilla Kubernetes cluster.

Stay tune :)

**Comment by alosadagrande** [comment]
Already done in https://github.com/metal3-io/metal3-docs/pull/74 PR at metal3-docs repository
