### ISSUE TITLE
Metal3 Try-It page refers to scripts that have been deleted

### ISSUE THREAD

**Issue by kedmison** [metal3-io/metal3-io.github.io#201]
The Metal3-io Try-it page, in [section 2.5. Directly Provision BareMetalHost](https://metal3.io/try-it.html#25-directly-provision-baremetalhost) refers to two scripts, provision_host.sh and deprovision_host.sh. They are missing from the metal3-dev-env repository.

I found that the provision_host.sh and deprovision_host.sh scripts were deleted in this commit: https://github.com/metal3-io/metal3-dev-env/commit/6b4715bae8749628de30fba8e6d1f1c83a04805c

Should the docs be updated to remove section 2.5? refer to a new way of directly provisioning bare metal hosts?

**Comment by fmuyassarov** [comment]
Thanks for reporting it. Those scripts were indeed removed. This should be fixed in https://github.com/metal3-io/metal3-io.github.io/pull/202
