### ISSUE TITLE
Post titles not rendered correctly

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#26]
While working on #25 , the titles displayed for regular 'markdown' formatting are not properly differentiated from regular text:

![image](https://user-images.githubusercontent.com/312463/63935402-a9242b80-ca5d-11e9-98f0-775792ba8eb4.png)

Source code for markdown is at that PR (#25) that also 'reenables' blogs section on index.html and removes the sample articles

**Comment by matthewcarleton** [comment]
This should be fixed. I will note that using only one `#` for the heading won't provide any specific styling other than margins b/c there is already an H1 on the page as the post title. There are styles for h2,h3,h4,h5,h6 with specific visual styling for h2,h3. If we need more just let me know and I can add it :)

**Comment by iranzo** [comment]
Moved all titles one level down in articles, closing this.

Thanks!
