### ISSUE TITLE
Footer Icons

### ISSUE THREAD

**Issue by Collins-Omariba** [metal3-io/metal3-io.github.io#272]
The footer Icons look a bit odd on mobile, can I correctly align them at the bottom with a bit of styling for a good UI.

**Comment by Collins-Omariba** [comment]
![Uploading Screenshot_20230307-112342.png…]()

**Comment by kodervine** [comment]
Hi Collins,

Are you an outreachy applicant?

If so, you should reach out to the mentors directly about the tasks for the contribution phase. You can find their contact details here - https://www.outreachy.org/outreachy-may-2023-internship-cohort/communities/metal3/#improve-the-metal3-io-website-and-documentation

**Comment by Collins-Omariba** [comment]
Yeah, let me do so.

**Comment by Rozzii** [comment]
Thanks for the help @kodervine.
I will accept this ticket, it is a valid improvement, would the outreachy intern(s) fix this @elfosardo  ?

**Comment by Collins-Omariba** [comment]
@Rozzii , I do want to fix it, only that I have not yet been assigned the issue.

**Comment by elfosardo** [comment]
@Rozzii we've recently clarified with the Outreachy applicants that they're free to contribute to the website if they want, we're of course not going to stop them.
Although we've assigned aleady other tasks for the first round of Outreachy and they don't include issues here on the website repository at the moment, so for the first round we won't take into considerations contributions other than what we've assigned directly.

**Comment by iamatifmoin** [comment]
can I work on this, please?

**Comment by okerekechinweotito** [comment]
@elfosardo 
Please Is this issue still eligible to be worked on

**Comment by Rozzii** [comment]
I am not sure what was decided related to this issue, so I have assigned @okerekechinweotito  feel free assign someone else if you want @elfosardo .

**Comment by elfosardo** [comment]
thanks @Rozzii
we can leave it like this for the time being
we'll reassign it in case there's no movement in the next week

**Comment by SafeEHA** [comment]
Please assign this to me
