### ISSUE TITLE
HTTPS not enforced for http://metal3.io/

### ISSUE THREAD

**Issue by SafeEHA** [metal3-io/metal3-io.github.io#273]
Description:
Currently, GitHub Pages is not enforcing HTTPS on your website, which is a significant security concern for users. Users should be automatically redirected to use HTTPS, but I have noticed that this is not happening.

Screenshot:
![WhatsApp Image 2023-03-07 at 10 07 58](https://user-images.githubusercontent.com/98215429/223378654-8fb6d6af-548a-4017-96c3-7d7a10f896e6.jpeg)

How to fix: 
[Enforcing HTTPS for your GitHub pages](https://docs.github.com/en/pages/getting-started-with-github-pages/securing-your-github-pages-site-with-https#enforcing-https-for-your-github-pages-site)

**Comment by akankshat05** [comment]
Can I work on this issue ?

**Comment by zaneb** [comment]
I tested and it redirected fine, but then I realised that I have the HTTPSEverywhere extension installed :laughing:

I enabled the enforce setting and it appears to be doing the trick (without the extension, heh) now. Thanks for spotting this!

/triage accepted
/close
