### ISSUE TITLE
Search bar is getting overlapped.

### ISSUE THREAD

**Issue by RitamSamant** [metal3-io/metal3-io.github.io#287]
The search bar is getting overlapped with the `Try it!`'s '!'.

![Screenshot (46)](https://user-images.githubusercontent.com/91908473/231899580-7803b746-70b2-4c09-b4b7-02f54ed79538.png)

**Comment by tuminoid** [comment]
HI @RitamSamant, thanks the the report!

Technically, it is not overlapping, it is placed right next to it with no pixels in between. So it is ugly, but not overlapping :smiley: Little padding be nice, I agree.

**Comment by iamatifmoin** [comment]
Hi @oeuvars 

I guess #289 can be closed since [#1](https://github.com/oeuvars/metal3-io.github.io/pull/1) already resolves the issue. 
Both PRs are the same.

**Comment by Rozzii** [comment]
Thanks for the fix @oeuvars
/close

**Comment by lentzi90** [comment]
> Hi @oeuvars
> 
> I guess #289 can be closed since [#1](https://github.com/oeuvars/metal3-io.github.io/pull/1) already resolves the issue. Both PRs are the same.

That PR was not for this repository so it didn't fix the issue.
/open

**Comment by lentzi90** [comment]
#289 is merged. Now we can close this.
/close
