### ISSUE TITLE
Block codes doesn't differentiate too much

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#30]
![image](https://user-images.githubusercontent.com/312463/63996922-55691f00-cafd-11e9-92ae-e99ae07359a4.png)

vs

![image](https://user-images.githubusercontent.com/312463/63996934-5c902d00-cafd-11e9-9c86-98bc782c773d.png)

**Comment by matthewcarleton** [comment]
ya this is just how it spits it out. I can see about changing the style though
