### ISSUE TITLE
Update the landing page

### ISSUE THREAD

**Issue by elfosardo** [metal3-io/metal3-io.github.io#330]
Provide a detailed description of the goals / mission of Metal3 right in the beginning of the landing page (https://metal3.io/).
Provide a brief component overview with links.

**Comment by SafeEHA** [comment]
> /assign @SafeEHA

Thanks @elfosardo 
I’m currently finishing up this with #326

**Comment by SafeEHA** [comment]
PRs 
#319 
 #320 
 #321 
 #322 
 #328 
 #329 
 are all related to this issue

**Comment by SafeEHA** [comment]
PR #332 closes this issue

**Comment by elfosardo** [comment]
great job, thanks!
