### ISSUE TITLE
Add a contributor page summarising how to help the community and what kind of help we are looking for.

### ISSUE THREAD

**Issue by elfosardo** [metal3-io/metal3-io.github.io#340]
This feature should include the following tasks:
- create a contributor page with a brief description of the metal3 community and link to the community page
- add an "how to" section mentioning what type of help is needed and how to provide that.  Make sure to include Ironic.
- add links and advices for best practices for collaboration with an open source community
- add a link to the current open issues in case someone wants to get hands on quickly

**Comment by SafeEHA** [comment]
Please assign this to me

**Comment by elfosardo** [comment]
this has been completed
thanks @SafeEHA
