### ISSUE TITLE
[Docs] Update the README.md of metal3-io to show new X logo (formerly Twitter)

### ISSUE THREAD

**Issue by Viveksati5143** [metal3-io/metal3-io.github.io#353]
The use of old twitter bird logo can be replaced at most of the places with the new X one
<img width="960" alt="image" src="https://github.com/metal3-io/metal3-io.github.io/assets/100852245/43ffc567-b917-42c9-b5dd-9adfd2886881">

I would like to work on this as my first issue in metal3-io.

**Comment by dtantsur** [comment]
Our twitter account does not seem active, maybe we should remove it (especially given the questionable ownership of X/Twitter). In any case, the request seems valid.

/triage accepted

**Comment by Viveksati5143** [comment]
> Our twitter account does not seem active, maybe we should remove it (especially given the questionable ownership of X/Twitter). In any case, the request seems valid.
> 
> /triage accepted

Sure, so can you assign me so i can remove it from the footer of pages?
