### ISSUE TITLE
Categories generation causes broken links

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#36]
![image](https://user-images.githubusercontent.com/312463/64002837-4e490d80-cb0b-11e9-8e27-362f8a111731.png)

Seems that categories defined in article got an extra "/" at the end that causes htmlproofer to detect link as broken

**Comment by iranzo** [comment]
I've moved in the post 'categories' to 'tags' in the meantime

**Comment by matthewcarleton** [comment]
I'm not sure about this one. I've seen the error but this was intended. When we have a long list of categories this will allow an easy way to get to them on the categories page.

**Comment by iranzo** [comment]
Fixed, _layouts/posts.html contained trailing "/" that made it fail, now fixed in master
