### ISSUE TITLE
Some Images not displaying in blog page

### ISSUE THREAD

**Issue by SafeEHA** [metal3-io/metal3-io.github.io#367]
I noticed that in the [blog page](https://metal3.io/blog/2023/05/05/Scaling_part_1.html) where the individual blogs are displayed, the search icon, dark mode icon and CNCF logo are not displayed. The terminal returns an error of "not found"

<img width="630" alt="Screen Shot 2023-10-19 at 09 56 20" src="https://github.com/metal3-io/metal3-io.github.io/assets/98215429/422ed534-a34a-4248-a6f8-0bece47dad80">

<img width="1085" alt="Screen Shot 2023-10-19 at 09 56 48" src="https://github.com/metal3-io/metal3-io.github.io/assets/98215429/cf9e486d-84d0-44ff-af88-208cea0a58f4">

<img width="281" alt="Screen Shot 2023-10-19 at 09 56 40" src="https://github.com/metal3-io/metal3-io.github.io/assets/98215429/b640685e-e648-4cfb-9e74-dafdcfb77037">

**Comment by elfosardo** [comment]
I confirm the issue, it's happening for me too

**Comment by Rozzii** [comment]
The issue has been solved partially on the main blog page, but if someone opens an actual blog post then images are still not displayed properly .
I have asked help from
/cc @peppi-lotta 
/remove-lifecycle stale
![image](https://github.com/metal3-io/metal3-io.github.io/assets/21961855/60f7e073-4609-40ea-a8fe-421cbdfbf2bb)
![image](https://github.com/metal3-io/metal3-io.github.io/assets/21961855/b3c40bf3-3a0b-4d57-bebb-99588c3ef45d)
