### ISSUE TITLE
BMO e2e introduction blog post

### ISSUE THREAD

**Issue by lentzi90** [metal3-io/metal3-io.github.io#371]
We should spread the word about the new BMO e2e tests!
The blog post should mention at least the following:

- The e2e tests are meant to be flexible so that they can be run both in VM-based CI and on real hardware
- They are much faster than the CAPM3 e2e tests, while still extensively testing BMO
- How the CI jobs are set up to work with VMs
- That it is possible to run the tests with the fixture provider for quick sanity checks

**Comment by Rozzii** [comment]
This is not an urgent but still welcomed improvement.
/lifecycle frozen
