### ISSUE TITLE
[Flake] yaspeller pre-commit failures in metal3-io.github.io repo

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-io.github.io#378]
Example: https://github.com/metal3-io/metal3-io.github.io/actions/runs/7376713815/job/20069816380?pr=377 in https://github.com/metal3-io/metal3-io.github.io/pull/377

yaspeller is failing in pre-commit to seemingly being unable to read its configuration at times.

**Comment by tuminoid** [comment]
https://github.com/metal3-io/metal3-io.github.io/pull/379 upgraded the yaspeller, but as shown in https://github.com/metal3-io/metal3-io.github.io/pull/380 it is now giving false positives and not detecting any typos.

**Comment by tuminoid** [comment]
https://github.com/metal3-io/metal3-io.github.io/pull/381 removes yaspeller.

**Comment by Rozzii** [comment]
/close
I think this can be closed as yaspeller was removed.
