### ISSUE TITLE
There's like a 'text box'  with scroll

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#41]
![image](https://user-images.githubusercontent.com/312463/64121951-8b79fd80-cda0-11e9-88ec-8162e6b10c71.png)

Looks a bit 'strange'

**Comment by matthewcarleton** [comment]
ah :( I have scrollbars turned off in chrome by default so I missed this. There is an overflow on this content area b/c of none breaking lines of code in the docs/try it pages. I'll see if I can improve it.
