### ISSUE TITLE
FAQ needs to be added once content is added

### ISSUE THREAD

**Issue by matthewcarleton** [metal3-io/metal3-io.github.io#5]

**Comment by iranzo** [comment]
How do we 'reenable' it once content is there? 

I wanted to contrib 'operator' to FAQ so that we can start building-up the section

Thanks,

**Comment by iranzo** [comment]
I thought it was initially a folder with '.md' files, added my pr #11 to this file

Thanks

**Comment by iranzo** [comment]
Ok, merged the first one on Operator, I think we should remove the 'first question' to leave this one and expand from there and show them *again* on the website.

**Comment by iranzo** [comment]
Closed via #18
