### ISSUE TITLE
When defining 'inks' for codeblocks there's no coulouring

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#50]
Usually when setting:

```yaml
api: patata

```
the output is rendered using different 'inks' based on the format specified, which allows to easily read through the code provided (bash, yaml, python, go, etc)

The output on the webpage is always grey

**Comment by iranzo** [comment]
![imagen](https://user-images.githubusercontent.com/312463/64255061-ed617100-cf20-11e9-90a0-e00c7e1a6d8a.png)

**Comment by matthewcarleton** [comment]
This one is a little tricky. I can only style what Markdown spits out in terms of classes and elements that are wrapped in a tag. I'm not sure how specific we can get with this.
