### ISSUE TITLE
Scroll bars in text areas

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#52]
Even with latest 'master', there's still a text box as described initially in #41 and appearing for example in screenshoot at #51

**Comment by matthewcarleton** [comment]
Which Browser/OS are you seeing this in?

**Comment by iranzo** [comment]
Chrome 76.0.3809.132 (Build oficial) On Fedora 30
    Firefox 68.0.2 (64-bit) (also on Fedora 30)
