### ISSUE TITLE
Broken link checker fails to check url with question mark

### ISSUE THREAD

**Issue by tuminoid** [metal3-io/metal3-io.github.io#522]
Here, broken link checker chokes on the question mark. The link itself works.

/triage accepted
/assign @peppi-lotta 

### Errors in https://metal3.io/blog/2024/10/24/Scaling-Kubernetes-with-Metal3-on-Fake-Node.html

* [ERROR] [https://cluster-api.sigs.k8s.io/clusterctl/commands/describe-cluster.html?highlight=describe%20cluster#clusterctl-describe-cluster](https://cluster-api.sigs.k8s.io/clusterctl/commands/describe-cluster.html?highlight=describe%20cluster#clusterctl-describe-cluster) | Failed: Network error: error sending request for url (https://cluster-api.sigs.k8s.io/clusterctl/commands/describe-cluster.html?highlight=describe%20cluster#clusterctl-describe-cluster)

**Comment by peppi-lotta** [comment]
It seems this URL was not flagged in the latest run. I have run the check a couple of times as well and haven't seen this happen again. I suggest we close this issue for now and keep an eye out in case it happens again.

**Comment by tuminoid** [comment]
Let's close this next Monday, if it is not present in the weekly report.
