### ISSUE TITLE
Add analytics account

### ISSUE THREAD

**Issue by matthewcarleton** [metal3-io/metal3-io.github.io#6]
We have the code, just need the account info.

**Comment by iranzo** [comment]
In other places we do use Adobe, but if we can enable it, let's create an account or an org, start with that and later move to definitive one or use it to 'compare' between several of them

Also, enabling GA and Bing 'claim' on website, allows to get search performance reports even coverage or issues with navigation for mobile devices, etc

**Comment by iranzo** [comment]
`UA-146522880-1`

**Comment by iranzo** [comment]
We'll need to also enable domain verification for search console to work

**Comment by iranzo** [comment]
![image](https://user-images.githubusercontent.com/312463/63834505-b82fae80-c975-11e9-8ee6-0daa74641086.png)

First data already incoming

**Comment by iranzo** [comment]
Done
