### ISSUE TITLE
Content Security Policy missing

### ISSUE THREAD

**Issue by iranzo** [metal3-io/metal3-io.github.io#63]
https://www.dareboost.com/en/report/d_15d773f2190b99843ddb4b550?reportIds=d_15d773f2190b99843ddb4b550

**Comment by matthewcarleton** [comment]
@dhellmann @iranzo I'm not 100% on what needs to be done for this. Are either of you familiar with it?

**Comment by iranzo** [comment]
Nothing on your side, sorry! it's server-side
