### ISSUE TITLE
need directions for running validation tests locally

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/metal3-io.github.io#72]
It looks like the CI jobs run some validation against the content. It would be nice to know how to run those locally before creating a pull request.

**Comment by iranzo** [comment]
It validates that all links are reachable, the other 'test' is just build the site, which is at 'readme' for using a container to validate that it renders properly

**Comment by iranzo** [comment]
doc is at https://github.com/metal3-io/metal3-io.github.io/blob/master/README.md  the only difference is that CI also validates broken links as said before, but not just on new article but on all the website

**Comment by dhellmann** [comment]
I see checks with names "Header rules", "Pages changed", "Redirect rules", and "Mixed content". What are those?

**Comment by iranzo** [comment]
That's for netlify if you use 'traffic rules' to load balance received requests between sites, etc, we just use them for the page preview, so you can disregard those.

**Comment by iranzo** [comment]
https://www.netlify.com/docs/continuous-deployment/

**Comment by iranzo** [comment]
@dhellmann is this clear now? something else that needs clarification?

**Comment by iranzo** [comment]
Closing out of inactivity
