### ISSUE TITLE
blog titles do not link to articles

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/metal3-io.github.io#74]
The titles of blog posts on https://metal3.io/blog/index.html are styled in the same way as the "read more" links, which makes me think I should be able to click on them. Can we make the titles links and replace the "read more" links?

**Comment by ptrnull** [comment]
yes! I realized it too, it's quite of annoying to go to the title and find that there is no link, /cc @iranzo I think it's a templating issue

**Comment by iranzo** [comment]
https://5d78b1ab4f9dda00070cc626--metal3.netlify.com/blog/index.html
