### ISSUE TITLE
circle around twitter icon on blog post pages is very large

### ISSUE THREAD

**Issue by dhellmann** [metal3-io/metal3-io.github.io#75]
The circle around the twitter image on a page like https://metal3.io/blog/2019/09/11/Baremetal-operator.html is much much larger than the icon itself when viewed in Safari on macOS 10.14.6.
![Screen Shot 2019-09-10 at 5 24 36 PM](https://user-images.githubusercontent.com/43312/64651663-04580580-d3f0-11e9-8326-f88354f98450.png)

**Comment by ptrnull** [comment]
in firefox 68.0.2 (64-bit) over fedora it looks good 
/cc @matthewcarleton

**Comment by iranzo** [comment]
In Chrome fedora
![image](https://user-images.githubusercontent.com/312463/64682296-88a69900-d481-11e9-8da4-858885cfece5.png)

Looks good
